<?php

namespace AllDigitalRewards\ChannelAdvisor\Entities;

class Order extends AbstractEntity
{
/*"ID": 25273704,
      "ProfileID": 12345678,
      "SiteID": 930,
      "SiteName": "Jet",
      "SiteOrderID": "125977339633",
      "SecondarySiteOrderID": "2ab4557edee54641b4547dc817890ee6",
      "SellerOrderID": null,
      "CheckoutSourceID": null,
      "CreatedDateUtc": "2016-09-25T23:47:03Z",
      "ImportDateUtc": "2016-09-26T03:42:30.947Z",
      "PublicNotes": null,
      "PrivateNotes": "Base - Base - $102.00",
      "SpecialInstructions": "",
      "TotalPrice": 1699.99,
      "TotalTaxPrice": 0,
      "TotalShippingPrice": 0,
      "TotalShippingTaxPrice": null,
      "TotalInsurancePrice": 0,
      "TotalGiftOptionPrice": 0,
      "TotalGiftOptionTaxPrice": null,
      "AdditionalCostOrDiscount": 0,
      "EstimatedShipDateUtc": null,
      "DeliverByDateUtc": null,
      "ResellerID": null,
      "FlagID": 0,
      "FlagDescription": null,
      "OrderTags": null,
      "DistributionCenterTypeRollup": "SellerManaged",
      "CheckoutStatus": "Completed",
      "PaymentStatus": "Cleared",
      "ShippingStatus": "Unshipped",
      "CheckoutDateUtc": "2016-02-29T12:43:19Z",
      "PaymentDateUtc": "2016-02-29T12:43:19Z",
      "ShippingDateUtc": "2016-03-01T04:45:26.21Z",
      "BuyerUserId": "jonathan.doe.jet.447094560291@example.com",
      "BuyerEmailAddress": "jonathan.doe.jet.447094560291@example.com",
      "BuyerEmailOptIn": false,
      "OrderTaxType": "Standard",
      "ShippingTaxType": "Standard",
      "GiftOptionsTaxType": "Standard",
      "PaymentMethod": "Jet",
      "PaymentTransactionID": null,
      "PaymentPaypalAccountID": null,
      "PaymentCreditCardLast4": "",
      "PaymentMerchantReferenceNumber": null,
      "ShippingTitle": null,
      "ShippingFirstName": "Jonathan",
      "ShippingLastName": "Doe",
      "ShippingSuffix": "Sr",
      "ShippingCompanyName": null,
      "ShippingCompanyJobTitle": null,
      "ShippingDaytimePhone": "1234567890",
      "ShippingEveningPhone": null,
      "ShippingAddressLine1": "45 Main Street",
      "ShippingAddressLine2": "",
      "ShippingCity": "Stevens",
      "ShippingStateOrProvince": "PA",
      "ShippingPostalCode": "17578",
      "ShippingCountry": "US",
      "BillingTitle": null,
      "BillingFirstName": "Jonathan",
      "BillingLastName": "Doe",
      "BillingSuffix": "Sr",
      "BillingCompanyName": "",
      "BillingCompanyJobTitle": null,
      "BillingDaytimePhone": "1234567890",
      "BillingEveningPhone": null,
      "BillingAddressLine1": "45 Main Street",
      "BillingAddressLine2": "",
      "BillingCity": "Stevens",
      "BillingStateOrProvince": "PA",
      "BillingPostalCode": "17578",
      "BillingCountry": "US",
      "PromotionCode": null,
      "PromotionAmount": 0
 * */
}